//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORAMANTENIMIENTO
    {
        public int IDBITACORAMANTENIMIENTO { get; set; }
        public Nullable<int> IDEQUIPO { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHABITACORAM { get; set; }
        public Nullable<int> TIPOMANTENIMIENTO { get; set; }
        public Nullable<System.DateTime> HORAINI { get; set; }
        public Nullable<System.DateTime> HORAFIN { get; set; }
        public string ESTADOINI { get; set; }
        public string ESTADOFIN { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
