//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORAINSTALACION
    {
        public int IDBITACORAINSTALACION { get; set; }
        public Nullable<int> IDPROCINSTALACION { get; set; }
        public Nullable<System.DateTime> FECHABITACORAIN { get; set; }
        public string DETALLES { get; set; }
    
        public virtual PROCINSTALACION PROCINSTALACION { get; set; }
    }
}
