//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA()
        {
            this.LINECOMPRAs = new HashSet<LINECOMPRA>();
        }
    
        public int IDCOMPRA { get; set; }
        public Nullable<int> IDINST { get; set; }
        public Nullable<int> IDEMP { get; set; }
        public Nullable<decimal> TOTALCOMPRA { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
        public string DEPSOLICITANTES { get; set; }
        public Nullable<int> TIPOCONTRATACION { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINECOMPRA> LINECOMPRAs { get; set; }
    }
}
