//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresas()
        {
            this.usuarios = new HashSet<usuarios>();
        }

        [Display(Name = "Id Empresa")]
        public int id { get; set; }
        public int tipo { get; set; }

        [Display(Name = "Nombre Empresa")]
        public string nombre { get; set; }

        [Display(Name = "Direccion")]
        public string direccion { get; set; }

        [Display(Name = "Telefono Contacto")]
        public string telefono { get; set; }

        [Display(Name = "Email contacto")]
        public string email_contacto { get; set; }

        [Display(Name = "NIT")]
        public string nit { get; set; }

        [Display(Name = "Nombre Representante")]
        public string nombre_responsable { get; set; }

        [Display(Name = "DUI Responsanble")]
        public string dui_responsable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios> usuarios { get; set; }

        [Display(Name = "Tipo Empresa")]
        public virtual tipos_empresa tipos_empresa { get; set; }
    }
}
