//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.COMPRAs = new HashSet<COMPRA>();
            this.USUARIOs = new HashSet<USUARIO>();
            this.INSTITUCIONs = new HashSet<INSTITUCION>();
        }
    
        public int IDEMP { get; set; }
        public Nullable<int> IDTIPO { get; set; }
        public string NOMBREEMP { get; set; }
        public string DIRECCIONEMP { get; set; }
        public string TELEFONOCONTACTO { get; set; }
        public string EMAILCONTACTO { get; set; }
        public string NITEMP { get; set; }
        public string NOMBRERESPEMP { get; set; }
        public string DUIRESPEMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA> COMPRAs { get; set; }
        public virtual TIPOEMPRESA TIPOEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTITUCION> INSTITUCIONs { get; set; }
    }
}
