//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos_solicitud
    {
        public int equipo { get; set; }
        public int solicitud { get; set; }
        public int cantidad { get; set; }
    
        public virtual equipos equipos { get; set; }
        public virtual solicitudes solicitudes { get; set; }
    }
}
