//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPO()
        {
            this.BITACORAMANTENIMIENTOes = new HashSet<BITACORAMANTENIMIENTO>();
            this.PROCINSTALACIONs = new HashSet<PROCINSTALACION>();
        }
    
        public int IDEQUIPO { get; set; }
        public Nullable<int> IDESEQUIPO { get; set; }
        public Nullable<int> IDCATEQUIPO { get; set; }
        public Nullable<int> IDLINEACOMPRA { get; set; }
        public string NUMEROSERIAL { get; set; }
        public Nullable<decimal> ANOGARANTIA { get; set; }
        public string DETALLEGARANTIA { get; set; }
        public Nullable<int> ESTADOGARANTIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORAMANTENIMIENTO> BITACORAMANTENIMIENTOes { get; set; }
        public virtual CATEGORIAEQUIPO CATEGORIAEQUIPO { get; set; }
        public virtual LINECOMPRA LINECOMPRA { get; set; }
        public virtual ESPECIFICACIONEQUIPO ESPECIFICACIONEQUIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCINSTALACION> PROCINSTALACIONs { get; set; }
    }
}
