//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos_fisicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipos_fisicos()
        {
            this.mantenimientos = new HashSet<mantenimientos>();
            this.proc_instalacion = new HashSet<proc_instalacion>();
        }
    
        public string num_serial { get; set; }
        public System.DateTime fecha_fabricacion { get; set; }
        public decimal tiempo_garantia { get; set; }
        public string detalles_garantia { get; set; }
        public int estado_garantia { get; set; }
        public int departamento { get; set; }
        public int esp_equipo { get; set; }
    
        public virtual departamentos departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mantenimientos> mantenimientos { get; set; }
        public virtual esp_equipos esp_equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proc_instalacion> proc_instalacion { get; set; }
    }
}
