//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIFICACIONEQUIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIFICACIONEQUIPO()
        {
            this.EQUIPOes = new HashSet<EQUIPO>();
        }
    
        public int IDESEQUIPO { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public Nullable<decimal> POTENCIA { get; set; }
        public Nullable<decimal> CAPACIDADBTU { get; set; }
        public Nullable<decimal> CORRIENTEOPERACION { get; set; }
        public string ANIOFABRICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPO> EQUIPOes { get; set; }
    }
}
