//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINECOMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LINECOMPRA()
        {
            this.EQUIPOes = new HashSet<EQUIPO>();
        }
    
        public int IDLINEACOMPRA { get; set; }
        public Nullable<int> IDCOMPRA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPO> EQUIPOes { get; set; }
    }
}
