//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.MENU1 = new HashSet<MENU>();
            this.PERFILPERMISOes = new HashSet<PERFILPERMISO>();
        }
    
        public int IDENTMENU { get; set; }
        public Nullable<int> MEN_IDENTMENU { get; set; }
        public string NOMBREOPCION { get; set; }
        public string RUTAACCESO { get; set; }
        public Nullable<int> PORDEFECTO { get; set; }
        public byte ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENU1 { get; set; }
        public virtual MENU MENU2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFILPERMISO> PERFILPERMISOes { get; set; }
    }
}
