//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoBADCon : DbContext
    {
        public proyectoBADCon()
            : base("name=proyectoBADCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BITACORAINSTALACION> BITACORAINSTALACIONs { get; set; }
        public virtual DbSet<BITACORAMANTENIMIENTO> BITACORAMANTENIMIENTOes { get; set; }
        public virtual DbSet<CATEGORIAEQUIPO> CATEGORIAEQUIPOes { get; set; }
        public virtual DbSet<COMPRA> COMPRAs { get; set; }
        public virtual DbSet<EMPRESA> EMPRESAs { get; set; }
        public virtual DbSet<EQUIPO> EQUIPOes { get; set; }
        public virtual DbSet<ESPECIFICACIONEQUIPO> ESPECIFICACIONEQUIPOes { get; set; }
        public virtual DbSet<INSTITUCION> INSTITUCIONs { get; set; }
        public virtual DbSet<LINECOMPRA> LINECOMPRAs { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<PERFIL> PERFILs { get; set; }
        public virtual DbSet<PERFILPERMISO> PERFILPERMISOes { get; set; }
        public virtual DbSet<PERFILUSUARIO> PERFILUSUARIOs { get; set; }
        public virtual DbSet<PROCINSTALACION> PROCINSTALACIONs { get; set; }
        public virtual DbSet<RECPASSWORD> RECPASSWORDs { get; set; }
        public virtual DbSet<TIPOEMPRESA> TIPOEMPRESAs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
