//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILUSUARIO
    {
        public int IDUSUARIO { get; set; }
        public int IDPERFIL { get; set; }
        public byte ESTADO { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
