//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfiles_permisos
    {
        public int perfil { get; set; }
        public int menu { get; set; }
        public int estado { get; set; }
    
        public virtual menus menus { get; set; }
        public virtual perfiles perfiles { get; set; }
    }
}
