//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCINSTALACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROCINSTALACION()
        {
            this.BITACORAINSTALACIONs = new HashSet<BITACORAINSTALACION>();
        }
    
        public int IDPROCINSTALACION { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<int> IDEQUIPO { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public byte ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORAINSTALACION> BITACORAINSTALACIONs { get; set; }
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
