//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoBADEntities : DbContext
    {
        public proyectoBADEntities()
            : base("name=proyectoBADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora_instalacion> bitacora_instalacion { get; set; }
        public virtual DbSet<bitacora_mantenimiento> bitacora_mantenimiento { get; set; }
        public virtual DbSet<categorias_equipo> categorias_equipo { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<empresas> empresas { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<equipos_fisicos> equipos_fisicos { get; set; }
        public virtual DbSet<equipos_solicitud> equipos_solicitud { get; set; }
        public virtual DbSet<esp_equipos> esp_equipos { get; set; }
        public virtual DbSet<instituciones> instituciones { get; set; }
        public virtual DbSet<linea_compra> linea_compra { get; set; }
        public virtual DbSet<mantenimientos> mantenimientos { get; set; }
        public virtual DbSet<menus> menus { get; set; }
        public virtual DbSet<perfiles> perfiles { get; set; }
        public virtual DbSet<perfiles_permisos> perfiles_permisos { get; set; }
        public virtual DbSet<perfiles_usuarios> perfiles_usuarios { get; set; }
        public virtual DbSet<proc_instalacion> proc_instalacion { get; set; }
        public virtual DbSet<rec_password> rec_password { get; set; }
        public virtual DbSet<solicitudes> solicitudes { get; set; }
        public virtual DbSet<tipos_empresa> tipos_empresa { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
