//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rec_password
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string ram_hash { get; set; }
        public int estado { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
