//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.BITACORAMANTENIMIENTOes = new HashSet<BITACORAMANTENIMIENTO>();
            this.PERFILUSUARIOs = new HashSet<PERFILUSUARIO>();
            this.PROCINSTALACIONs = new HashSet<PROCINSTALACION>();
            this.RECPASSWORDs = new HashSet<RECPASSWORD>();
        }
    
        public int IDUSUARIO { get; set; }
        public Nullable<int> IDEMP { get; set; }
        public Nullable<int> IDINST { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public byte ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORAMANTENIMIENTO> BITACORAMANTENIMIENTOes { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFILUSUARIO> PERFILUSUARIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCINSTALACION> PROCINSTALACIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECPASSWORD> RECPASSWORDs { get; set; }
    }
}
