//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoBAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.perfiles_usuarios = new HashSet<perfiles_usuarios>();
            this.rec_password = new HashSet<rec_password>();
            this.departamentos1 = new HashSet<departamentos>();
            this.mantenimientos = new HashSet<mantenimientos>();
            this.proc_instalacion = new HashSet<proc_instalacion>();
        }
    
        public string email { get; set; }
        public Nullable<int> empresa { get; set; }
        public Nullable<int> departamento { get; set; }
        public string nombre_completo { get; set; }
        public string password { get; set; }
        public int estado { get; set; }
    
        public virtual departamentos departamentos { get; set; }
        public virtual empresas empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfiles_usuarios> perfiles_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rec_password> rec_password { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<departamentos> departamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mantenimientos> mantenimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proc_instalacion> proc_instalacion { get; set; }
    }
}
